### ISSUE TITLE
Update postcss-import to latest - Fixes webpack issues

### ISSUE THREAD

**Issue by dalphyx** [TrySound/postcss-easy-import#11]
According to [postcss-import  issue #207](https://github.com/postcss/postcss-import/issues/207), it's better to update`postcss-import` to version > 8.1.0.

**Comment by simonsmith** [comment]
Thanks for this. I'll look to upgrade `postcss-import` very soon

**Comment by simonsmith** [comment]
Fixed in https://github.com/TrySound/postcss-easy-import/commit/b99df8de8e7f75c9f43878bdfa3ca807637693aa
