### ISSUE TITLE
Cannot get glob modules to work

### ISSUE THREAD

**Issue by nwmcsween** [TrySound/postcss-easy-import#15]
A very simple testcase is `@import asm.css/lib/align-self/*.css;` where asm.css is a node_module, it seems easy import isn't resolving it for some reason?

Relevant files

postcss.config.js (using postcss-cli)
````
module.exports = (ctx) => ({
  'no-map': true,
  plugins: {
    'postcss-easy-import': {},
    'postcss-reporter': {}
  }
})
````

building:
`./node_modules/.bin/postcss $file -o $ofile`
where $file is
`@import "asm.css/lib/align-self/*.css";`
of which asm.css/lib/align-self/* exists and has files in node_modules

**Comment by TrySound** [comment]
@simonsmith Can glob resolver look in `node_modules`?

**Comment by simonsmith** [comment]
Currently the glob functionality only works when resolving relative pathnames. I'm sure we could just combine the two as a new feature.

**Comment by TrySound** [comment]
There's [glob-parent](https://github.com/es128/glob-parent) package which can help with this.
