### ISSUE TITLE
~ prefix support

### ISSUE THREAD

**Issue by SPAHI4** [TrySound/postcss-easy-import#19]
IDEA (Webstorm) supports prefix `~` by default. So support of this prefix would be nice.
![image](https://user-images.githubusercontent.com/1670998/27191145-8982dfac-51ff-11e7-8554-58bdde7f6660.png)
![image](https://user-images.githubusercontent.com/1670998/27191152-91c69866-51ff-11e7-851c-5f573587695a.png)

**Comment by TrySound** [comment]
I don't think using tilde is good choice. There's nodejs notation `./`, `../` which will work in browsers. Node uses `module/path` for magic resolving. Webpack will support only `module/path` notation for styles soon. I guess browsers will let resolve similar. Tilde increases fragmenting.
