### ISSUE TITLE
Compatibility with .pcss

### ISSUE THREAD

**Issue by riccardoerra** [TrySound/postcss-easy-import#28]
Using PostCSS and before was just using as extensions `.css`.
So for example having something like this works:
```
@import "vars.css";
@import "fonts.css";
@import "all.css";
@import "main.css";
@import "../../components/**/*.css";
```

I'm now in the process of changing the extensions of the stylesheet files to `.pcss` and the plugins seems not to work.
```
@import "vars.pcss";
@import "fonts.pcss";
@import "all.pcss";
@import "main.pcss";
@import "../../components/**/*.pcss";
```

All the files get correctly imported apart from the one inside components subfolders.

Any idea why and/or what to do to try to fix this issue?

**Comment by equinusocio** [comment]
Hi, you have to set the correct extension in options..
https://github.com/TrySound/postcss-easy-import#extensions
