### ISSUE TITLE
postcss-cli --watch doesn't watch the imported sources

### ISSUE THREAD

**Issue by saiichihashimoto** [TrySound/postcss-easy-import#3]
Using postcss-cli like `postcss -w` doesn't watch the imported sources. I don't remember the context, but it ended up involving hardcoding something into postcss-cli. Hopefully this can be solved in postcss-easy-import so we can avoid hardcoding into postcss-cli again. Maybe this warrants a scalable solution with postcss-cli for this.

https://github.com/postcss/postcss-import/issues/88
https://github.com/code42day/postcss-cli/issues/33
https://github.com/code42day/postcss-cli/pull/35

**Comment by TrySound** [comment]
@saiichihashimoto `postcss-easy-import` is `postcss-import` extension. You can use the same API.
