### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [TrySound/postcss-easy-import#40]
**Thanks for your PostCSS plugin!** 

As you probably know, [PostCSS 8] was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide].

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[migration guide]: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by equinusocio** [comment]
Have to drop this plugin now due to missing support for PostCSS 8. The fix is easy, just update the underlying `postcss-import` deps

**Comment by wommy** [comment]
found a fix

https://github.com/dimitrinicolas/postcss-import-ext-glob

**Comment by lmoval** [comment]
I am working on it

**Comment by simonsmith** [comment]
[4.0.0](https://www.npmjs.com/package/postcss-easy-import/v/4.0.0)

Thanks @lmoval @morels

**Comment by lmoval** [comment]
Lovely! 💯
