### ISSUE TITLE
Make prefix optional

### ISSUE THREAD

**Issue by mehcode** [TrySound/postcss-easy-import#5]
With `prefix: "_"` declared I'd like the import to be able to import either `test.scss` or `_test.scss` with a preference to the prefixed one if both are found.

**Comment by timgrafton** [comment]
This isn't working for me. Still not falling back to non prefixed version of file.

**Comment by simonsmith** [comment]
Could you provide more detail?

**Comment by timgrafton** [comment]
It's working now, must have been a problem elsewhere. :)
